### ISSUE TITLE
pdf version won't open

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#101]
Since last night I've been getting this error on trying to open the PDF version of the book: 
![image](https://user-images.githubusercontent.com/23551540/48750381-8b55b900-ecca-11e8-92da-e8dd2586bfc3.png)

**Comment by jeffreyhanson** [comment]
I had a look at the release and the atlas pdf had a red cross next to it. This was like the time when you entered the command to start uploading the assets and killed it before it finished, so I suspect this might be caused by two separate builds trying to upload the atlas at the same time (e.g. caused by two commits that were pushed in rapid succession). So, I manually deleted the pdf in the release and restarted the build for the latest commit. Let's see if this fixes it.

**Comment by jeffreyhanson** [comment]
This indeed fixed the problem - the pdf version of the atlas can now be opened.
