### ISSUE TITLE
Add Buff-breasted Sandpiper and Western Gerygone

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#107]
Given that the dataset now includes records for both these, it's probably a good idea to add them (unless that's already happened and I've missed it). Perhaps @dbl3raf wants to try this (without the assistance / training wheels of @jeffreyhanson 😃 )?

**Comment by Louis-Backstrom** [comment]
I've just tried to add these two species, not sure if it has worked yet - I followed all of the instructions on the FAQ. I wasn't quite sure what the listings were for each species (@dbl3raf , where is the database where species are listed for QLD and nationally?), and I haven't yet been able to setup my computer so that I can build the assets myself, but I'm working on that - next project.

Hopefully this has worked, but if not it'll be a good learning experience.

**Comment by Louis-Backstrom** [comment]
Unsurprisingly, that failed :( - haven't worked out why yet. @jeffreyhanson ?

Edit: missed a hyphen, trying again.

Edit edit: nope, still failing. Seems to have a problem with the species profile?

**Comment by Louis-Backstrom** [comment]
```
Quitting from lines 7542-7543 (brisbane-bird-atlas.Rmd) 
Error in render_species_table(species_name) : 
  assets/tables/Calidris-subruficollis.rds does not exist
Calls: system.time ... withVisible -> eval -> eval -> render_species_table
In addition: Warning message:
In data.table::fread(record_path, data.table = FALSE) :
  Found and resolved improper quoting out-of-sample. First healed line 28315: <<URN:CornellLabOfOrnithology:EBIRD:OBS528575425	2017-10-31 14:59:46.0	9755	species	Dollarbird	Eurystomus orientalis			1				Australia	AU	Queensland	AU-QLD	Brisbane	AU-QLD-BRI					Harold Keilly Park	L1004598	H	-27.3107926	153.0226851	1978-11-18	06:00:00	obsr453532	S38883397	Stationary	P21	EBIRD	45			1	1		0	1	0		"Bald Hills Swamp". Showeers, mild, overcast		>>. If the fields are not quoted (e.g. field separator does not appear within any field), try quote="" to avoid this warning.

Timing stopped at: 67.3 9.312 52.2
Execution halted
Exited with code 1
```

It's complaining the BBSP doesn't have a table file associated with it from what I can tell and yet there's nothing in `/assets/tables` other than the `.gitkeep` file which is empty?

**Comment by jeffreyhanson** [comment]
Yeah, the `./assets/tables` directory should just contain a `.gitkeep` file (just like the `./assets/figures`, `./assets/surveyor-sheets`, `./assets/figures`, `./assets/maps`, `./assets/widgets`, `./assets/profile`). This is because when the automated build services start building the atlas, they (1) download the zipfiles from the storage release (i.e. https://github.com/bird-team/brisbane-bird-atlas/releases/tag/v.0.0.1), (2) unzip the contents of the zipfiles into empty directories, and (3) start building the atlas using the images/rdata files. So, the reason it's throwing an error is because, after downloading the tables zip file and unziping it, it can't find the `assets/tables/Calidris-subruficollis.rds` file. And it can't find this file, because the assets need to be made for this species and pushed to storage release.

So once we resolve #65, I can build all the assets---including the new assets for these two species---and then we can rebuild the atlas with these new species.

**Comment by Louis-Backstrom** [comment]
Right, that makes sense then.

**Comment by jeffreyhanson** [comment]
I just tried making the assets for these two species and it appears that they don't have any records inside the study area in the eBird data. Does that sound right?

**Comment by Louis-Backstrom** [comment]
They should do - BBSP 5 records (maybe fewer as some might be shared) from Tinchi Tamba - Deepwater Bend Square, and WEGE probably 10-15 records from the Whites Hill Square. Are you using the October dataset?

**Comment by jeffreyhanson** [comment]
Nevermind - looks like there's something funny happening in the data checks.

**Comment by dbl3raf** [comment]
these two have added just fine, and build succeeded - closing issue
