### ISSUE TITLE
Warning on surveyor sheet asset build - format requires nonempty <title> element

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#110]
On building surveyor sheets, I'm now seeing the following warning appearing. It's taking 15 seconds or so to churn out each warning, so will add hours and hours to the asset build process as it's doing a warning for each of hundreds of files. Any thoughts?

![image](https://user-images.githubusercontent.com/23551540/49685747-fdd0f080-fb34-11e8-8975-0263e9dee7cb.png)

**Comment by dbl3raf** [comment]
The build completed successfully despite these warnings, so fixing it is a low priority - unless its trivially easy to do?

**Comment by jeffreyhanson** [comment]
The warnings always appear for me when building the sheets, it might be that these warnings do not appear when rebuilding from cache? It does take >5 seconds to create a single surveyor sheet (due to downloading imagery from Google and finding observer names from eBird). Have you tried increasing the threads parameter in the paramter YAML file to reduce run time?

**Comment by dbl3raf** [comment]
Yep it was a new set of warnings this time around, that preceded the main build of the surveyor sheets. I have the threads on 2, which seems to help. The build finished fine, so it's no worries - I'll close the issue.
