### ISSUE TITLE
Updates to acknowledgements

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#112]
With the recent update to Oct-18's eBird release, I anticipate that we've got a couple (probably like 50?) new eBirders who have submitted checklists to Brisbane and therefore should have their names on the acknowledgements page. @dbl3raf, how did you go about getting the first list of names and how should we maintain it with each database update?

**Comment by dbl3raf** [comment]
I did it as a manual job with the data download - it's a bit trickier now the real names have been removed from the eBird database output. @jeffreyhanson has a web scraper that harvests names for the surveyor sheets - we could probably co-opt that code to provide a full list of all observer names in the download.

**Comment by jeffreyhanson** [comment]
I think adding this to the build process would substantially increase build times, so we would have to create an additional "asset" that contains all the pre-computed observer names. Unfortunately, this would probably substantially increase the time taken to build the assets as it seems that finding the names for the leader boards is the bit that takes up most of the time creating the surveyor sheets.

**Comment by jeffreyhanson** [comment]
So, I don't have any ideas on how we could do this without increasing build time or increasing the asset creation time - both of which seem to already be taking a long time?

**Comment by Louis-Backstrom** [comment]
Can we somehow split up assets into multiple groups based on how often we expect to be updating them?
For instance, the acknowledgements will only need to be updated every time we update the database, so it's okay if that takes a while. Other assets will be updated more regularly e.g. surveyor sheets whenever we change the descriptions.

In theory though, everything should calm down a bit after launch - we'll only be updating smaller things once the whole Atlas is drafted?

**Comment by jeffreyhanson** [comment]
Well, a lot of the data processing has cache functionality. This means that if the code detects that an asset doesn't need to be remade then it won't try remaking the asset. So, when updating the atlas using new eBird data, this means that updating all the assets will take a very long time. But, when updating surveyor sheets, then this should hopefully not take as long since all the graphs/maps/widgets/tables will already be made. I worry that splitting the assets into two different types will mean a lot of work on my end, and also make updating the atlas a lot harder because there's more manual steps that will need to be executed.

**Comment by dbl3raf** [comment]
I agree / given all this I think we should close this discussion with no changes to the code
