### ISSUE TITLE
Option to "reset zoom" on map

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#128]
Not sure how much control we have over the map widget but it would be good if there was a button (perhaps below the +/- zoom ones) to reset the zoom back to the Brisbane extent it defaults to - it can be annoying when you're playing around to get it back to a nice setting.

Additionally, I'm not sure we need the ability to zoom out to the entire globe - could that be restricted to just the entire Brisbane extent (including marine cells)?

**Comment by jeffreyhanson** [comment]
Great idea! I'll push an update which should add in a home button and then remake the assets.

**Comment by Louis-Backstrom** [comment]
Awesome, thanks @jeffreyhanson

**Comment by jeffreyhanson** [comment]
Ok - the maps now have a "reset view" and have a restricted map domain to Brisbane (I've already pushed the new assets to GitHub). Ideally, the reset view button would have an icon, bu alas this functionality isn't provided by the _leafem_ R package which lets us add reset buttons to the maps so that would require a lot more work. I'll push the final code change related to this issue and close this issue.
