### ISSUE TITLE
Grid square size?

### ISSUE THREAD

**Issue by Louis-Backstrom** [bird-team/brisbane-bird-atlas#143]
I was under the impression that each cell was 2x2km (ie 4km2), but looking more closely that appears to be incorrect, rather the squares are ~3.14km2 or about 1.77x1.77km?

![image](https://user-images.githubusercontent.com/44354406/59956052-2e74e800-94d1-11e9-816f-3900ff10123a.png)

I suppose it'd probably be pretty painful to change this now, but just wanted to make note in case this was unintentional

**Comment by jeffreyhanson** [comment]
Yeah, spatial stuff is tricky. There are multiple different coordinate systems (i.e. schemes for converting the 3d egg-shaped Earth into a 2d flat map, e.g. Mercator) and methods for calculating distances from longitude/latitude data that won't always give the same answer depending on where you are on the planet. The grid cells are the "correct" size but only when measured using the same coordinate system that they were generated in (i.e. Mercator, https://epsg.io/3857). Specifically, I chose this coordinate system because its the only coordinate system natively supported by our interactive mapping technology (i.e. leaflet). You're right, the grid cells aren't exactly 2 x 2 km (defined as when measured using a coordinate system designed for highly accurate distances in eastern Australia), but if I used a different coordinate system then the some grid cells would appear larger than others when displayed on the interactive maps which might by confusing for some readers. So, it's the best compromise I could come up with - what do you think? Please let me know if what I've wrote doesn't make sense and I can try to explain the rationale again?

**Comment by Louis-Backstrom** [comment]
Yeah okay, figured it had something to do with CRS etc. Doesn't worry me, but maybe a note in the methods section to explain it would be worthwhile?

**Comment by jeffreyhanson** [comment]
Good idea - I'll do that now.

**Comment by jeffreyhanson** [comment]
Done (I accidentally referenced the wrong issue in the commit, 54dc6910e8312c3ea758dff1021ce5d6cd6cd12e).
