### ISSUE TITLE
Static maps

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#16]
I've been working on the code to produce the static maps that will appear in the offline (pdf) version. I have included an example below, @dbl3raf can you let me know if you want any changes (e.g. colors, text sizes, remove map coordinates, etc)?

![anseriformes-anseranatidae-anseranas-semipalmata](https://user-images.githubusercontent.com/3610005/40460048-302163dc-5f48-11e8-99de-6152648bd178.png)

**Comment by dbl3raf** [comment]
General concept looks good: 

1. expand map coverage to include Moreton Island
2. remove coordinates from map edge
3. change underlying statistic (and legend title) to Reporting Rate (calculated as the proportion of complete checklists in which the species of interest appears; this will be expressed throughout the atlas as a percentage instead of a proportion to make it more accessible to a non-specialist reader)
4. distinguish between true zeroes and no data, i.e. grid cells with zero complete checklists are "no data" for reporting rate, and should be, e.g. made transparent
5. coupled with a way of achieving (4) above - you could make a boundary around the Brisbane LGA, and have the no data grid cells just transparent
6. Make the grey of the landmass substantially lighter so it becomes background rather than heavily dominating the map

top stuff - can I see another iteration before approving?

**Comment by jeffreyhanson** [comment]
Sure, I'll update the code and post another version.

**Comment by jeffreyhanson** [comment]
The eBird data contains records collected from different sampling methodologies. Specifically, the `PROTOCOL_TYPE` column the records the following values: "eBird - Casual Observation", "Historical",  "eBird - Traveling Count", "eBird - Stationary Count", "eBird - Exhaustive Area Count", and "eBird Random Location Count". Which value(s) should be included in the reporting rate?

**Comment by dbl3raf** [comment]
Your values for PROTOCOL_TYPE are out of date I think? The possible values in my most recent download are:

Area
Banding
BirdLife Australia 20min-2ha survey
BirdLife Australia 500m radius search
Historical
Incidental
Nocturnal Flight Call Count
Random
Stationary
Traveling

Complete checklists are in fact signalled by a different field - a value of 1 in the column ALL_SPECIES_REPORTED, except there is one annoying referential error in the underlying eBird data. Any checklist with the PROTOCOL_TYPE = Incidental should be treated as ALL_SPECIES_REPORTED = 0, even where ALL_SPECIES_REPORTED = 1 in the eBird download. eBird HQ are aware of this problem, but they don't want to fix it.

**Comment by jeffreyhanson** [comment]
Ok thanks for clarifying this. I'm using a 2016 version of the data, so that explains why i'm missing a bunch of the different sampling protocols. I'll update my copy of the data when I get a chance, but I've updated the map code based on your suggestions. I've copied in one of the maps below, let me know if there's any more changes I can make to it.

![anseriformes-anatidae-dendrocygna-arcuata](https://user-images.githubusercontent.com/3610005/40464849-f926686e-5f60-11e8-87b0-52f085b9c43e.png)

**Comment by jeffreyhanson** [comment]
Here's another idea for highlighting Brisbane in the map.

![anseriformes-anatidae-dendrocygna-arcuata](https://user-images.githubusercontent.com/3610005/40465105-6585e4de-5f62-11e8-9760-bc6376d014fc.png)

**Comment by dbl3raf** [comment]
This second one is absolutely perfect, great job!

**Comment by jeffreyhanson** [comment]
Ok, I'll close this issue then. If you change your mind or come up with any ideas for improving the maps, feel free to reopen this issue and we can chat more about it.
