### ISSUE TITLE
Reference style

### ISSUE THREAD

**Issue by jeffreyhanson** [bird-team/brisbane-bird-atlas#27]
What reference style should we use? As discussed this morning, it sounds like it would be good to have a number-based reference style. Is there a particular journal reference style we should emulate? This would be easiest for me because then I can just download pre-made reference style files and tell the book to use them for generating the references.

**Comment by dbl3raf** [comment]
Landscape and Urban Planning is the closest journal to my preferred choice. Main things I prize are full journal names rather than abbreviated names, and avoided clutter of commas and other punctuations. Landscape and Urban Planning is one of the few journals not to abbreviate names, although they do indulge in quite a few commas etc. The perfect reference format for me is:

Hanson JO, Rhodes JR, Riginos C & Fuller RA (2017) Environmental and geographic variables are effective surrogates for genetic variation in conservation planning. Proceedings of the National Academy of Sciences of the United States of America, 114, 12755-12760.

But I recognise that writing our own style code would take lots of time and isn't a high priority. So Landscape and Urban Planning it is, unless you happen to know of one more like the above.

**Comment by jeffreyhanson** [comment]
Ok can do
