### ISSUE TITLE
Issues with map / colour ramps

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#40]
Sorry to do this, but I thought again it was better to call these early rather than later down the track.

I've decided that it is too hard to visually distinguish zero from nonzero reporting rates on the maps. I suggest two possible design tweaks to address this, and we can discuss whether these are feasible / would work etc before implementing.

1. Simplify the base map to make a plainer background. Not saying we should go this far, but e.g.:

![2016-11-29 rf_iphone_20170214 012](https://user-images.githubusercontent.com/23551540/41498085-a1598996-71a7-11e8-991a-ddde0aa65f7f.JPG)

I don't know if it's possible to add a satellite / basic mapping selector onto the map in the same way that google maps has? The map could default by opening onto the plain map, and then the user could select the satellite map to explore around if desired. The PDF version would only use the plain map. If that's tricky, going completely to a plain map throughout is probably best.

2. Continue to use transparent for squares with no checklists, but use a plain neutral colour for zero reporting rate, such as pale grey. This would make the nonzero reporting rates really stand out.

**Comment by jeffreyhanson** [comment]
With regards to your points,

1. I could create a background for the interactive map that has specific colors/conventions but this could take a week or two. Instead, I would recommend that we use a pre-made map background that is close enough to what you want for the atlas. Here is a catalogue of some different map backgrounds (https://leaflet-extras.github.io/leaflet-providers/preview/), if you see any that you like I can update the atlas to use them. Also, it is indeed possible to add multiple backgrounds and use radio-buttons to flick between them, so let me know if you want to use one of these in addition to the current map background, or if you want entirely different ones. Note that different backgrounds have different zoom levels, so I would recommend verifying that the maps you like have a high enough zoom to be suitable for the atlas.

2. Sure, we already have two different shades of grey in the map, so I wonder if people will be able to differentiate between the three shades? If we adopt the same color scheme as in the picture (blue ocean, grey land mass, white study area), then this shouldn't be a problem. Alternatively, we could color the squares zero reporting rates with black since darker colors mean lower reporting rates?

**Comment by dbl3raf** [comment]
1. The most appropriate map from the catalogue seems to be Esri world gray canvas. But if we can have a button so a user can switch to satellite-type view as well, that would be awesome.

2. I think we have to go grey, but should instead apply that grey to cells with no data, and leave the zero reporting rate cells transparent. This way, we will vastly reduce the amount of grey on the map, and it will clearly show areas that need more survey effort. One we get to the point of achieving full coverage of all grid cells in all seasons, there will be no grey on the map.

**Comment by jeffreyhanson** [comment]
It appears that including multiple groups of radio-buttons for the interactive maps is tricky (i.e. having one set of radio buttons for the basemaps and another set of radio buttons for the heat maps). So, the available options are: we can either just use a single basemap and use radio buttons for the heat maps, or use multiple basemaps and use checkboxes for the heat maps (this is undesirable because it means that multiple heat maps can be overlaid at once, I've included a screenshot below showing this). What would you prefer?

![screenshot](https://user-images.githubusercontent.com/3610005/41572401-e38f098e-73ba-11e8-877f-174536e14876.png)

**Comment by dbl3raf** [comment]
Exciting stuff! I think we should use a single thematic basemap and radio buttons for the heat maps. Couple of points arising from looking at this:

1. Maybe make the Brisbane extent border somewhat narrower as it currently obscures the view of some of the edge cells.

2. Just to clarify, a grid cell should be empty (=transparent) if there is >1 compete checklist and no record of the species, but shaded grey if there are no checklists. Once all grid cells are surveyed for a particular map, there will be no grey checklists.

**Comment by jeffreyhanson** [comment]
I've updated the online interactive maps (e.g. see here for magpie goose; https://brisbanebirds.com/magpie-goose-anseranas-semipalmata.html#magpie-goose-anseranas-semipalmata) and the offline maps (see below for example) to follow these specifications (noting that the range maps are handled in a separate issue). @dbl3raf, can you let me know if I've missed anything or if there are any more changes you would like to the maps? 

![anseranas-semipalmata](https://user-images.githubusercontent.com/3610005/41697595-d88c9b48-755c-11e8-8574-dc72ca5373ea.png)

**Comment by dbl3raf** [comment]
Looking brilliant @jeffreyhanson! A few minor tweaks:

1. I think we should show the Brisbane extent on the offline maps.
2. Change title of first map from "Annual" to "All year"
3. Technically white on these five maps means "Rate = 0%" rather than "Absent", since there might be records from non-complete checklists in those cells. Maybe we could change the legend from "Absent" to "0% Rate" or "Rate = 0%" - I can't decide which is better

**Comment by jeffreyhanson** [comment]
Ok can do. I think "0% Rate" is better because it minimizes the width of the legend.

**Comment by jeffreyhanson** [comment]
@dbl3raf, I've added the detection maps (#41), added a black border around Brisbane to the offline maps, changed the title of the first map to "All Year", and set the "Absent" label as "0% Rate". Do you have any more requests for changing the appearance of the maps?

**Comment by dbl3raf** [comment]
Awesome @jeffreyhanson no further requests from me

**Comment by jeffreyhanson** [comment]
Ok great, I'll close this issue then.
