### ISSUE TITLE
Map to show records from non-complete checklists where there are none from complete lists

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#41]
Because our current mapping only gives reporting rate from complete checklists, the maps miss out squares that only have records from non-complete checklists. This will result in significant under-mapping particularly of scarcer species, which are often recorded incidentally. We could deal with this by adding another map that includes all records (maybe just a presence / absence map, and / or by specifying that any square without any complete checklists but with records of the species from non-complete checklists is given a small but nonzero reporting rate to ensure it appears on the map. Any thoughts on this?

**Comment by dbl3raf** [comment]
It has also occurred to me there is a time aspect to this same problem as well. There will be many cases where there is a pre-2005 record from a grid cell, but nothing from 2005-onwards. So, I think this "total" map should also include records from all years in the database, not just the "atlas" years of 2005-present.

**Comment by dbl3raf** [comment]
More generally, this is the type of code I will probably want to be able to modify, so hopefully I'll be able to get my head around how to edit the record selection criteria in the underlying code.

**Comment by jeffreyhanson** [comment]
I like the idea of putting this data into it's own map, rather than modifying values in the existing maps. 

What is the goal/message to communicate with this map? If the goal is to provide an upper estimate of species' distributions across Brisbane (i.e. reduce omission and increase comission errors) then this map could show binary data indicating if the species was detected in each grid cell (under any sampling protocol)?

Alternatively, I recall that one of the motivations for the atlas was to motivate targeted sampling across Brisbane. Since none of other maps really do this, perhaps this map could highlight areas that would substantially benefit from more complete checklists? If there are grid cells that have detections under any sampling protocol but do not have any proper checklists inside them then perhaps this map could highlight them (i.e. as binary). Perhaps instead of using a "one checklist" threshold we could instead apply a higher threshold (e.g. identify grid cells that have >1 detection under any sampling protocol but have <100 total checklists)? Do you know of any studies that can tell us how many checklists are needed to get a good idea of habitat usage?

**Comment by dbl3raf** [comment]
Thanks for clarifying that we need to think about the message being portrayed. The goal is precisely to provide an upper estimate of a species' distribution. To this end, let's go with your first suggestion, which is a binary presence / absence map showing all records from any type of checklist ever. This map shows the spatial distribution of all records, and the RR maps show the spatial pattern of relative abundance. Awesome!

**Comment by dbl3raf** [comment]
Just a small follow-up, it would be great to be able to control the start date on this map via a parameter. Could this also be conditional? The reason I ask is that for some of the rare species I would want to include all records from all time. For some of the commoner species I might be interested in a map within the traditional atlas time window of 2005 onward.

**Comment by jeffreyhanson** [comment]
Sure, I'll open a new issue for the species-specific start dates.

**Comment by jeffreyhanson** [comment]
I'll push a new of the atlas to GitHub with detection maps. If you have any requests concerning the styling of these maps, raise them in #40.
