### ISSUE TITLE
Devise grid cell labelling scheme

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#64]

**Comment by dbl3raf** [comment]
what are the dimensions of the matrix of atlas squares? If there's any way you could send me the shapefile of the current 2km grid that would be brilliant

**Comment by jeffreyhanson** [comment]
Sure, I've uploaded a zip file with the grid here ([grid.zip](https://github.com/bird-team/brisbane-bird-atlas/files/2194811/grid.zip)).

**Comment by dbl3raf** [comment]
So the decision is that any code will do for the grid cells, and they will in the end have unique text-based names, like Carindale South, Holland Park East etc. I suggest just using a uniquely indexed integer field to be a "primary key" and then add another text field, into which I can start putting names as we make them. You could always initialise the text field with the numbers used for the primary key, until I get around to replacing each square name. Does this work?

**Comment by jeffreyhanson** [comment]
Yeah, that works great. I can't remember - did we want to integrate the grid id's into the atlas itself? Or is this purely for the sampling sheets? I suppose we could have the interactive maps display the grid id if the grid cell is double clicked on?

**Comment by dbl3raf** [comment]
Initially this was for the survey sheets, but yes it would be brilliant if the grid square name could display if the cell is doubled clicked on - that would help the user identify a square. Maybe down the track we might be able to add a URL so they can download the survey sheet for that particular grid cell.

**Comment by jeffreyhanson** [comment]
I've updated the atlas so that the _data/grid/grid.shp_ file now contains the 2 x 2 km grid cells. It has an integer "id" field and a text "name" field in the attribute table. On the online version of the atlas, if you go to one of the species accounts (e.g. http://brisbanebirds.com/magpie-goose-anseranas-semipalmata.html#magpie-goose-anseranas-semipalmata), scroll down to the interactive map, then click on the "Grid" checkbox in the map, and then click on one of the black grid cells, you should see a popup. This popup currently displays the text in the "name" field of the grid shapefile - so once you've got "proper" names for all the grid cells then I can remake the interactive maps so they display the "proper" names.
