### ISSUE TITLE
Error in push_assetts

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#88]
Having trouble with push_assets - it starts zipping everything but then seems to fail when it starts the upload. I've tried restarting Docker, and also rebooting my machine. Any ideas?
![image](https://user-images.githubusercontent.com/23551540/48089723-ddb9c300-e250-11e8-969d-671564c5b9c9.png)

**Comment by jeffreyhanson** [comment]
Yeah that's strange - I haven't seen that before. Let's see if we can fix it during our meeting this arvo?

**Comment by jeffreyhanson** [comment]
We resolved this just now. It turns out Rich originally tried pushing the assets, then realised he forgot to update the assets, cancelled mid-upload, tried to push again later with new assets, and then got this error message. This error can be resolved by manually deleting the zip files in the release and then pushing the new assets. We've added some [info about this to the FAQ](https://github.com/bird-team/brisbane-bird-atlas/wiki/Frequently-asked-questions#i-get-an-error-when-i-try-pushing-new-assets). I'll close this issue now, but feel free to reopen this if the documentation isn't clear or you see this error again and the recommended fix doesn't work.
